Plat 448 geminize db helper
YourMechanic/postgres_utility pull request #1
Opened 2021-09-30 07:07 UTC by sachinsaxena1996

Plat-448 geminize db helper to create postgres_utility gem
Jira: https://yourmechanic.atlassian.net/browse/PLAT-448

2021-10-01 12:25 UTC, TruptiHosmani approved these changes

2021-10-01 16:49 UTC, siddyg requested changes

2021-10-01 16:49 UTC, siddyg commented on lib/postgres_utility.rb
> +    rails_connection.select_value("select version();")
@sachinsaxena1996 shouldnt we use single quotes here? 
Surprising that rubocop doesnt complain about this?
Can you double check other places in this PR to make sure we are using double quotes only for string interpolation

2021-10-04 15:38 UTC, siddyg approved these changes

2021-10-04 15:43 UTC, merged